root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/strict-type-checked"
  - "plugin:@typescript-eslint/stylistic-type-checked"
  - "plugin:deprecation/recommended"
reportUnusedDisableDirectives: true
parser: "@typescript-eslint/parser"
parserOptions: {projectService: true}
overrides:
  - files: "an_website/**"
    rules:
      "@typescript-eslint/no-non-null-assertion": "off"
    extends:
      - "plugin:compat/recommended"
    settings:
      lintAllEsApis: true
      polyfills:
        - "BigInt"
