root: true
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/strict-type-checked"
  - "plugin:@typescript-eslint/stylistic-type-checked"
reportUnusedDisableDirectives: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
overrides:
  - files: "*.js"
    extends: "plugin:@typescript-eslint/disable-type-checked"
    parserOptions:
      lib: ["es2022.full"]
