root: true
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/strict-type-checked"
  - "plugin:@typescript-eslint/stylistic-type-checked"
  - "plugin:deprecation/recommended"
reportUnusedDisableDirectives: true
parser: "@typescript-eslint/parser"
parserOptions: {projectService: true}
