extends:
  - "stylelint-config-standard-scss"
  - "stylelint-config-idiomatic-order"
  - "stylelint-prettier/recommended"
plugins:
  - "stylelint-no-unsupported-browser-features"
rules:
  "plugin/no-unsupported-browser-features":
    - true
    - severity: "warning"
      browsers: "Chrome 120, Firefox ESR, Safari 15.6"
reportDescriptionlessDisables: [true, { severity: "warning" }]
reportInvalidScopeDisables: true
reportNeedlessDisables: true
ignoreFiles:
  - "snow.css*"
