extends:
  - "stylelint-config-standard-scss"
  - "stylelint-config-idiomatic-order"
plugins:
  - "stylelint-no-unsupported-browser-features"
rules:
  "plugin/no-unsupported-browser-features":
    - true
    - severity: "warning"
ignoreFiles:
  - "snow.css*"
