name: Install dart-sass
description: Install dart-sass
inputs:
  version:
    description: The version of dart-sass
    required: false
    default: 1.77.5
  sass-proto-version:
    description: The version of the protobuf spec
    required: false
    default: 2.7.0
runs:
  using: composite
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: 3.3.4
    - name: Install buf
      shell: bash
      run: |
        wget -O /usr/local/bin/buf "https://github.com/bufbuild/buf/releases/download/v1.32.2/buf-$(uname -s)-$(uname -m)"
        chmod +x /usr/local/bin/buf
    - name: Install dart-sass
      shell: bash
      run: |
        pushd /tmp
        wget https://github.com/sass/dart-sass/archive/refs/tags/${{ inputs.version }}.tar.gz
        tar xf ${{ inputs.version }}.tar.gz
        cd dart-sass-${{ inputs.version }}
        dart pub get
        sed -i 's/"main"/"embedded-protocol-${{ inputs.sass-proto-version }}"/' tool/grind.dart
        dart run grinder protobuf
        sed -i "s/math.Random()/math.Random(0)/" lib/src/functions/*.dart
        dart compile exe bin/sass.dart --output /usr/local/bin/dart-sass
        cd ..
        rm -fr ${{ inputs.version }}.tar.gz dart-sass-${{ inputs.version }}
        popd
