name: Install dart-sass
description: Install dart-sass
inputs:
  tar_gz_release_file:
    description: The .tar.gz release file.
    required: false
    default: https://github.com/asozialesnetzwerk/dart-sass/releases/download/1.79.2%2Basozial/dart-sass-1.79.2+asozial-linux-x64.tar.gz
runs:
  using: composite
  steps:
    - name: Install dart-sass
      shell: bash
      run: |
        pushd "$(mktemp -d)"
        wget "${{ inputs.tar_gz_release_file }}"
        tar xf *.tar.gz
        rm *.tar.gz
        mv ./dart-sass/* /usr/local/bin/
        popd
