name: "Install dart-sass"
description: "Install dart-sass"
inputs:
  buf-version:
    description: the version of buf
    required: false
    default: 1.30.0
  dart-version:
    description: the version of dart
    required: false
    default: 3.3.2
  version:
    description: the version of dart-sass
    required: false
    default: 1.72.0
runs:
  using: "composite"
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.dart-version }}
    - name: Install buf
      env:
        VERSION_BUF: ${{ inputs.buf-version }}
      shell: bash
      run: |
        wget -O /usr/local/bin/buf https://github.com/bufbuild/buf/releases/download/v${VERSION_BUF}/buf-$(uname -s)-$(uname -m)
        chmod +x /usr/local/bin/buf
    - name: Install dart-sass
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        pushd /tmp
        wget https://github.com/sass/dart-sass/archive/refs/tags/${VERSION}.tar.gz
        tar xf ${VERSION}.tar.gz
        cd dart-sass-${VERSION}
        dart pub get
        dart run grinder protobuf
        sed -i "s/math.Random()/math.Random(0)/" lib/src/functions/*.dart
        dart compile exe bin/sass.dart --output /usr/local/bin/dart-sass
        cd ..
        rm -fr ${VERSION}.tar.gz dart-sass-${VERSION}
        popd
