plugins:
  - "compat"
ignorePatterns:
  - "static/js"
  - "vendored"
rules:
  compat/compat: "error"
  "@typescript-eslint/no-non-null-assertion": "off"
settings:
  lintAllEsApis: true
  polyfills:
    - "BigInt"
